//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOkul.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLNOTLAR
    {
        public int NOTİD { get; set; }
        public Nullable<byte> DERSİD { get; set; }
        public Nullable<int> OGRİD { get; set; }
        public Nullable<decimal> SINAV1 { get; set; }
        public Nullable<decimal> SINAV2 { get; set; }
        public Nullable<decimal> SINAV3 { get; set; }
        public Nullable<decimal> PROJE { get; set; }
        public Nullable<decimal> ORTALAMA { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TBLDERSLER TBLDERSLER { get; set; }
        public virtual TBLOGRENCİLER TBLOGRENCİLER { get; set; }
    }
}
